logger:
  type: stdout
  level: INFO

core:
  threads: 2
  runMode: once
  #runMode: repeat
  #sleepDuration: 30

common:
  github:
    timeout: 10
    rate_limit_wait_max: 120
    #username: name
    #password: password or pat
  docker:
    timeout: 10
  pypi:
    timeout: 10
  raw_html:
    timeout: 10

sources:
  - type: inline
    watchers:
      - name: PythonAlpineImage
        type: docker_registry
        repo: registry-1.docker.io
        image: python
        tag: 3.8.1-alpine3.11
        includes:
          - 3\.[0-9]+\.[0-9]+-alpine3\.11
        excludes:
          - .*rc[0-9]*-.*
          - .*[ab][1-9]-.*
          - 3\.[0-7]\..*
      - name: PyYAML PyPI
        type: pypi
        package: PyYAML
        version: 5.2
        includes:
          - 5\..*
        excludes:
          - .*[ab][1-9]$
      # Example only, use the github_commit type instead !
      - name: Raw Release Watcher
        type: raw_html
        page_url: https://github.com/Neraud/release-watcher/commits/main
        id: 3d0f1c0
        container_selector: ".js-navigation-container"
        item_selector: "li"
        id_selector: ".Button-withTooltip a .Button-label"
        id_attribute: ""
        date_selector: "relative-time"
        date_attribute: "datetime"
        reverse: False
        #basic_auth:
        #  username: your_username
        #  password: your_password
  - type: file
    path: github_watchers.yaml

outputs:
  - type: yaml_file
    path: out.yaml
    displayUpToDate: yes
  - type: csv_file
    path: out.csv
    displayHeader: yes
    displayUpToDate: yes
  - type: prometheus_file
    path: out.prom
  - type: prometheus_http
    port: 8080
